server:
  port: 8084
spring:
  application:
    name: service-consumer  #注册的服务名称，会在eureka中显示
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10087/eureka  #eureka地址
server-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #修改Ribbon的负载均衡策略为随机
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 设置hystrix的超时时间为6000ms

feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能
